spring:
  application:
    name: WalletMicroservice
  datasource:
    url: jdbc:postgresql://localhost:5432/suhoi
    username: suhoi
    password: suhoi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: db/changelog/changelog.xml
    default-schema: wallet_schema
    liquibase-schema: liquibase_service